{ config, lib, pkgs, inputs, ... }: 
{
    home.packages = with pkgs; [
        texlive.combined.scheme-full
        bluez
        bluez-tools
        blueman
        calibre
        cmake
        emacs
        enchant
        electron
        feishin
        firefox
        gcc
        gnumake
        gnuplot
        grimblast
        hugo
        hypridle
        hyprpaper
        hyprpicker
        hyprpolkitagent
        hyprshot
        jq
        mako
        #mgba
        languagetool
        libreoffice-qt
        libtool
        luajitPackages.luacheck
        nwg-displays
        nwg-look
        p7zip
        pandoc
        python3
        python3Packages.pip 
        python3Packages.black 
        python3Packages.flake8 
        python3Packages.mypy
        python3Packages.debugpy
        python3Packages.isort
        pwvucontrol
        ripgrep
        scrot
        slack
        slurp
        sqlite
        supersonic-wayland
        texlab
        teams-for-linux 
        thunderbird
        via
        vscode
        waybar
        wl-clipboard
        wlogout
        wordnet
        xfce.thunar
        zathura
        zoom-us
    ];
}
