{ config, lib, pkgs, inputs, ... }: 
{
    home.packages = with pkgs; [
        texlive.combined.scheme-full
        bluez
        bluez-tools
        blueman
        calibre
        cmake
        emacs
        electron
        feishin
        firefox
        gcc
        gnome-tweaks 
        gnome-weather 
        gnumake
        gnuplot
        grimblast
        jq
        mako
        mgba
        libreoffice-qt
        libtool
        luajitPackages.luacheck
        nwg-displays
        nwg-look
        p7zip
        python3
        python3Packages.pip 
        python3Packages.black 
        python3Packages.flake8 
        python3Packages.mypy
        python3Packages.debugpy
        python3Packages.isort
        pwvucontrol
        ripgrep
        scrot
        slack
        slurp
        texlab
        teams-for-linux 
        thunderbird
        via
        wl-clipboard
        xfce.thunar
        zathura
        zoom-us
    ];
}
